### ISSUE TITLE
Statistics fail to update

### ISSUE THREAD

**Issue by joubu** [WeblateOrg/weblate#10508]
### Describe the issue

The background job updating the stats is failing with the following error:

Failure while executing task: KeyError: 'stats_timestamp'

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Update a translation.

### Exception traceback

```pytb
weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,727: ERROR/1511] Failure while executing task: KeyError: 'stats_timestamp'                                                              weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,727: ERROR/ForkPoolWorker-8] Failure while executing task: KeyError: 'stats_timestamp'                                                  
weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,728: ERROR/1511] Failure while executing task: KeyError: {'signal': <Signal: task_failure providing_args={'exception', 'task_id', 'traceback', 'args', 'kwargs', 'einfo'}>, 'sender': <@task: weblate.utils.tasks.update_translation_stats_parents of weblate at 0x7fc9e3c49210>, 'task_id': '41c6e00c-36ec-4f25-99c4-35b7e471fa56', 'args': [7621], 'kwargs'
: {}, 'traceback': <traceback object at 0x7fc9cd31e240>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}                                                                                                         weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,728: ERROR/ForkPoolWorker-8] Failure while executing task: KeyError: {'signal': <Signal: task_failure providing_args={'exception', 'task
_id', 'traceback', 'args', 'kwargs', 'einfo'}>, 'sender': <@task: weblate.utils.tasks.update_translation_stats_parents of weblate at 0x7fc9e3c49210>, 'task_id': '41c6e00c-36ec-4f25-99c4-35b7e471fa56', 'args': [7621], 'kwargs': {}, 'traceback': <traceback object at 0x7fc9cd31e240>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}                                                                                             weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,728: ERROR/1511] Failure while executing task                                                                                           weblate-docker-weblate-1       | celery-celery stderr | Traceback (most recent call last):                                                                                                                           weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task                                                                weblate-docker-weblate-1       | celery-celery stderr |     R = retval = fun(*args, **kwargs)                                                                                                                        weblate-docker-weblate-1       | celery-celery stderr |                  ^^^^^^^^^^^^^^^^^^^^                                                                                                                        weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__                                                        weblate-docker-weblate-1       | celery-celery stderr |     return self.run(*args, **kwargs)                                                                                                                         
weblate-docker-weblate-1       | celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                         weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/tasks.py", line 79, in update_translation_stats_parents                                        
weblate-docker-weblate-1       | celery-celery stderr |     translation.stats.update_parents()                                                                                                                       weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 312, in update_parents                                                         
weblate-docker-weblate-1       | celery-celery stderr |     stat.update_stats()                                                                                                                                      weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 329, in update_stats                                                           
weblate-docker-weblate-1       | celery-celery stderr |     self.calculate_basic()                                                                                                                                   weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 337, in calculate_basic                                                        
weblate-docker-weblate-1       | celery-celery stderr |     self._calculate_basic()                                                                                                                                  weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 827, in _calculate_basic                                                       
weblate-docker-weblate-1       | celery-celery stderr |     stats[item] = max(values, default=time.time())                                                                                                           weblate-docker-weblate-1       | celery-celery stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                           
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 824, in <genexpr>                                                              weblate-docker-weblate-1       | celery-celery stderr |     values = (stats_obj.aggregate_get(item) for stats_obj in all_stats)                                                                                      
weblate-docker-weblate-1       | celery-celery stderr |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                  weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 225, in aggregate_get                                                          weblate-docker-weblate-1       | celery-celery stderr |     return self._data[name]                                                                                                                                  weblate-docker-weblate-1       | celery-celery stderr |            ~~~~~~~~~~^^^^^^                                                                                                                                  
weblate-docker-weblate-1       | celery-celery stderr | KeyError: 'stats_timestamp'                                                                                                                                  weblate-docker-weblate-1       | celery-celery stderr | [2023-11-29 12:29:32,728: ERROR/ForkPoolWorker-8] Failure while executing task                                                                               
weblate-docker-weblate-1       | celery-celery stderr | Traceback (most recent call last):                                                                                                                           weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task                                                                
weblate-docker-weblate-1       | celery-celery stderr |     R = retval = fun(*args, **kwargs)                                                                                                                        weblate-docker-weblate-1       | celery-celery stderr |                  ^^^^^^^^^^^^^^^^^^^^                                                                                                                        
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__                                                        weblate-docker-weblate-1       | celery-celery stderr |     return self.run(*args, **kwargs)                                                                                                                         
weblate-docker-weblate-1       | celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                         weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/tasks.py", line 79, in update_translation_stats_parents                                        
weblate-docker-weblate-1       | celery-celery stderr |     translation.stats.update_parents()                                                                                                                       weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 312, in update_parents                                                         
weblate-docker-weblate-1       | celery-celery stderr |     stat.update_stats()
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 329, in update_stats
weblate-docker-weblate-1       | celery-celery stderr |     self.calculate_basic()
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 337, in calculate_basic
weblate-docker-weblate-1       | celery-celery stderr |     self._calculate_basic()
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 827, in _calculate_basic
weblate-docker-weblate-1       | celery-celery stderr |     stats[item] = max(values, default=time.time()) 
weblate-docker-weblate-1       | celery-celery stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 824, in <genexpr>
weblate-docker-weblate-1       | celery-celery stderr |     values = (stats_obj.aggregate_get(item) for stats_obj in all_stats)
weblate-docker-weblate-1       | celery-celery stderr |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1       | celery-celery stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/stats.py", line 225, in aggregate_get
weblate-docker-weblate-1       | celery-celery stderr |     return self._data[name]
weblate-docker-weblate-1       | celery-celery stderr |            ~~~~~~~~~~^^^^^^
weblate-docker-weblate-1       | celery-celery stderr | KeyError: 'stats_timestamp'
```

### How do you run Weblate?

Docker container

### Weblate versions

weblate:bleeding (48863d1f4b3)

### Additional context

Related to https://github.com/WeblateOrg/weblate/issues/10473

**Comment by joubu** [comment]
Thanks a lot!

**Comment by joubu** [comment]
Even with the fix from #10508 (using bleeding docker image with HEAD 2f6cb95738f68b92c8e) we are still seeing:
![image](https://github.com/WeblateOrg/weblate/assets/671757/6669944e-8424-4263-a16c-5876faa934db)
![image](https://github.com/WeblateOrg/weblate/assets/671757/e3af6420-607d-45a9-9521-0fbd9750ab90)

And clicking the "1707 unfinished" link leads us to "No strings found!"

**Comment by nijel** [comment]
The stats will update only upon translation change, not automatically.

**Comment by joubu** [comment]
Yes, I have updated a translation, also flag one as "need editing".  But still marked as 90% translated.

**Comment by joubu** [comment]
None of the "Unfinished" number is correct.
https://translate.koha-community.org/projects/koha/master/#languages

French: 1731, but if you click on this number you get 2090
Spanish: 1707, 0
German: 1709, 217
Greek: 9673, 14752
and so on...

**Comment by joubu** [comment]
Another weirdness:
https://translate.koha-community.org/projects/koha/23-05/#languages (another category 23-05 instead of master)
German is 100% translated, it has the green tick. On hover text is: "1859 strings".
On the component list view: https://translate.koha-community.org/projects/koha/23-05/-/de/
1859 is the number for the first component "installer".

This "installer" component has the "source code repo" linked to the remote git repo, whereas other components within this 23-05 category point to it using weblate://koha/23-05/installer

**Comment by nijel** [comment]
0 is not expected, that means that the stats were not updated with the new code yet. So there is clearly an issue with updating category/language stats.

**Comment by laoneo** [comment]
Mounted the patch into my docker instance and it is now correctly updating.

**Comment by joubu** [comment]
Everything is fixed and working perfectly! Thanks again!

**Comment by laoneo** [comment]
Should this patch be in 5.3 (docker)? I'v updated and still have the issue, it only disappears when I mount the patched file with the fix from here.

**Comment by nijel** [comment]
The patch is there, but there is another issue which prevents component wide stat updates from being propagated. That one is fixed in c77ca8b2457e0e54f21b9c9e16238b78d0340509.

**Comment by laoneo** [comment]
Ok, thanks

**Comment by nijel** [comment]
I've just released 5.3.1 with the fix. Docker images will follow shortly.

**Comment by laoneo** [comment]
Thanks, can confirm that the fix is working.
