### ISSUE TITLE
For xliff file entries, context set incorrectly

### ISSUE THREAD

**Issue by efdee** [WeblateOrg/weblate#1099]
After upgrading to 2.5 we are noticing that in many cases the 'context' setting has been wrongly set:
![image](https://cloud.githubusercontent.com/assets/1038220/14954313/b39a5dd6-1071-11e6-86ae-dd98ad2d029f.png)

The value seems to be the base of the xliff filename (in this case Administration.Wpf.Models.FormulaType), then three slashes, then the actual context value. Really context here should be 'this'.

As a result of this, when trying to modify a translation, we get an error saying "Message not found in backend storage, it is probably corrupted.".

I've noticed that there have been some issues with xliff files with 2.5 - maybe this is related?

Thanks!
##

**Comment by nijel** [comment]
Upgrading to 2.6 should fix this, see #939 and #1021.

**Comment by efdee** [comment]
We have upgraded to 2.6, but I feel like I need to do something to remove the corrupted Context strings from the database? I tried ./manage.py loadpo --force project_name but that didn't seem to fix it.

**Comment by efdee** [comment]
I manually updated the database entries using `update trans_unit set context=substring_index(context, '/', -1) where context like '%///%';` which seems to have worked.

Maybe this helps future users, or you can tell me why that was a bad idea and what I should have done instead :-)

**Comment by efdee** [comment]
The context is now displayed correctly but we still get the "Message not found in backend storage, it is probably corrupted." message.

In the Weblate logfile we see this:
ERROR operra/tradingentitymarkettransaction/nl[19678]: message 62f0618398aff2826a5570d54197c84e on Operra/Trading.Entity.MarketTransaction - Dutch disappeared!
INFO operra/tradingentitymarkettransaction/nl: processing RA.Apps.Operra.Translations/nl/RA.Apps.Operra.Trading.Entity/RA.Apps.Operra.Trading.Entity.MarketTransaction.xliff, check forced

**Comment by nijel** [comment]
The ``./manage.py loadpo --force project_name`` should have fixed this, but maybe this is different problem than those fixed in 2.6. Does the loadpo revert the context back to the wrong one?

**Comment by efdee** [comment]
No, that leaves the contexts as they were. Didn't correct them when they were wrong but doesn't seem to be reverting them back to the incorrect version either.

**Comment by nijel** [comment]
That's strange, it should do one of these things....

**Comment by efdee** [comment]
What is also weird is that while I got the message about "message 62f0618398aff2826a5570d54197c84e on XX disappeared", I can definitely find entry 62f0618398aff2826a5570d54197c84e in the trans_unit table.

It makes me wonder whether it's maybe looking in the wrong place. But then again, that trans_unit table is the one where I updated the contexts and the frontend sure showed me that change.

Is there anything I can try or send you to help figure out this issue?

**Comment by nijel** [comment]
It means that it can not find it in the file, not in the database.

**Comment by nijel** [comment]
Can you try importing the project again, if that makes any difference?

**Comment by efdee** [comment]
What exactly do you mean with importing again? Deleting the component and adding it again?
Deleting the entire project would be a bit problematic since there's hundreds of components in the project.

**Comment by nijel** [comment]
For testing you can just import it again under different name or project to see how it behave.

**Comment by efdee** [comment]
It seems that adding a new component to the project with the same xliff file and settings as a malfunctioning one works perfectly.

**Comment by efdee** [comment]
I just reset all the existing contexts to their "broken" version (so now they all include the /// etc again) and the saving seems to work for all items now.

I'd rather have the context be the short version (so Cost in the example above) but at least this seems to be working for now.

**Comment by nijel** [comment]
I'm afraid the full context is needed for proper lookup, I would have to chech xliff module source code for that...
