### ISSUE TITLE
Changing component configuration results in internal server error

### ISSUE THREAD

**Issue by pchinery** [WeblateOrg/weblate#1357]
### Steps to reproduce
1. Install weblate 2.11 with the Dockerfile 
2. Create a component with Git repository that detects a few languages
3. Change the Git configuration

### Actual behaviour
The UI gives an internal server error. In the logs, we find a unique contraint violated as the language "zh_HANS" was tried to be added even though it was there already.

### Expected behaviour
Actually change the configuration ;-)

### Server configuration
 * Weblate 2.11
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.1.0
 * social-auth-app-django 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.9.1
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Can you please enable debug mode and post here full backtrace? I've been changing configuration several times and it always worked without problems, so you must be doing something different :-).

**Comment by pchinery** [comment]
Thank you for the quick answers!

This is what we have in the docker logs:

```
[09/Feb/2017 07:40:19] "GET /admin/jsi18n/ HTTP/1.0" 200 3217
INFO pdfcreator/messages: updating repository
INFO pdfcreator/messages: update took 0.99 seconds:
INFO pdfcreator/messages/zh_HANT: commiting Source/Languages/zh-HANT/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/da: commiting Source/Languages/da/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/nl: commiting Source/Languages/nl/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/lt: commiting Source/Languages/lt/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/nb_NO: commiting Source/Languages/nb-NO/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/pl: commiting Source/Languages/pl/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/ru: commiting Source/Languages/ru/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/sk: commiting Source/Languages/sk/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages/es: commiting Source/Languages/es/LC_MESSAGES/messages.po as XXXXXXXXXXXX
INFO pdfcreator/messages: rebase remote into repo
ERROR Internal Server Error: /admin/trans/subproject/4/change/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1441, in changeform_view
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 169, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 161, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 372, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 398, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1217, in full_clean
    self.clean()
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1322, in clean
    self.clean_lang_codes(matches)
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1153, in clean_lang_codes
    lang = Language.objects.auto_get_or_create(code=code)
  File "/usr/local/lib/python2.7/dist-packages/weblate/lang/models.py", line 219, in auto_get_or_create
    return self.auto_create(ret)
  File "/usr/local/lib/python2.7/dist-packages/weblate/lang/models.py", line 231, in auto_create
    pluralequation='n != 1',
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "lang_language_code_key"
DETAIL:  Key (code)=(zh_HANS) already exists.
```

I assume that this is the same as we would see in the debug mode output. If you should still want to look at that, please let me know.

**Comment by nijel** [comment]
Should be fixed, thanks for reporting.

**Comment by pchinery** [comment]
Thanks for looking into this so quickly. We still see the same exception thogu (with updated line numbers with the new code). Do you have any other idea to solve this?

**Comment by nijel** [comment]
Hmm, probably you already have some duplicated languages in the database. Can you check which auto generated languages are there in the admin interface, you can find it on following URL: `https://weblate.example.com/admin/lang/language/?q=generated`

**Comment by pchinery** [comment]
ah, you were right, we had "zh_Hans" and "zh_HANS" in the database. Now it works again :D

**Comment by nijel** [comment]
Originally the code was case sensitive, though that was really a bug here, so it should not appear again.
