### ISSUE TITLE
Notification emails with "String is available for translation" subject are rendered wrongly

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#14312]
### Describe the issue

When receiving Weblate notification email on my Android devices under Gmail => the display layout is broken.

🐛**The footer is displayed as a "column".**

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Subscribe to activity notification for a Weblate Translation Project with a Gmail account
2. Open notification email in Gmail Android app

### Expected behavior

The email should display correctly and shouldn't prevent user to click on buttons to directly access Weblate translation string.

### Screenshots

![Image](https://github.com/user-attachments/assets/857e1518-a6a9-4a2e-9d84-b68d50edab9a)

### How do you run Weblate?

weblate.org service

### Additional context

1. In previous Weblate versions the email layout was OK in Gmail under Android.
2. This layout pb seems to occur only on particular types of notification emails (and not on all weblate emails received) => yet layout bug identified on:
    - emails with subject "String is available for translation"

**Comment by ldmpub** [comment]
Changes seem to have be done 🤩.
First notification email received this morning looks good 👌.

I guess the change has been made on Weblate side rather than on Gmail Android app 😉.

**Comment by ldmpub** [comment]
Notice: it may not be the exact same type of notification email 🙃, the one received this morning and displaying Ok is "Suggestions awaiting" and not "new strings to translate" (please refer to emails subjects: there are différent in the 2 sreenshots).

![Image](https://github.com/user-attachments/assets/d398c57c-3497-4a5a-af14-37aa429f68fa)

**Comment by nijel** [comment]
We didn't make any change to this in the past months, so if things suddenly break and fixed, it's most likely caused by a third-party app. Or it can be that some kinds of notifications are rendered wrongly.

**Comment by ldmpub** [comment]
@nijel your 2d hypothesis sounds good => Can you please have a look at the "email template" used for the notification with the following subject https://hosted.weblate.org/translate/weblate/application/fr/?checksum=f307af4252f39fd2 ? It's the one which looks broken (at least under GMail app under Android). 

Thanks,

**Comment by nijel** [comment]
There is one issue in generated HTML which I've addressed in https://github.com/WeblateOrg/weblate/pull/14341, but it did affect all notifications, not just this one.

@meel-hd Do you have an idea how to debug this?

**Comment by meel-hd** [comment]
It is usually wrong html or css is modifying it weirdly. Check if the html structure is as it should be in the email and then check if some css is modifying the footer with `position` styles

**Comment by ldmpub** [comment]
Thanks @nijel ; I will check future notifications (maybe I'll get one tomorrow morning 🤞) and will let you know the result here by attaching a screenshot of the email.

**Comment by ldmpub** [comment]
Just to let you know => I didn't received any new notification yet.

**Comment by ldmpub** [comment]
Hi, I have received a new notification => see screenshot attached.

What I have noticed : 
* the problem is still there (vertical "footer" hides part of the mail content)
* but buttons to open string in weblate webapp seems to be more accessible (the vertical bar may have moved more, a little, to the left?).

![Image](https://github.com/user-attachments/assets/42fa08eb-0029-43b3-b348-91b9ad892f58)

**Comment by nijel** [comment]
We probably need to revisit the e-mail rendering. Apparently, Gmail strips parts of the CSS, so the footer alignment doesn't work. This is how it looks like in the web UI:

![Image](https://github.com/user-attachments/assets/cc0c3617-43fc-411c-9e11-63e36a2dd7c6)

**Comment by meel-hd** [comment]
@ldmpub would you please provide the email content, it would be a huge help in debugging this:
1.  Open gmail in your browser:
2. Open the Weblate email.
3. Click the 3 dots in the top right corner and click `Show original`
![Image](https://github.com/user-attachments/assets/b67ed3c1-41fb-4a9a-8ffa-989b758d890d)

4. Click the download original 
![Image](https://github.com/user-attachments/assets/c6829442-9f99-42fb-ac7d-76f44db595e5)
5. Upload the  downlaoded `.eml` file

Thank you!

**Comment by ldmpub** [comment]
Please find attached the email content (in a zip file eml files are not accepted in GitHub issues).

[\[Hosted Weblate\] Résumé _ Une chaîne est en attente de traduction.zip](https://github.com/user-attachments/files/19608326/Hosted.Weblate.Resume._.Une.chaine.est.en.attente.de.traduction.zip)

This eml match with the notification in the above screenshot => https://github.com/WeblateOrg/weblate/issues/14312#issuecomment-2774854178

**Comment by meel-hd** [comment]
@ldmpub Appreciate it. Now you may delete that file it contains your private email.

**Comment by nijel** [comment]
Hopefully fixed by https://github.com/WeblateOrg/weblate/pull/14473

**Comment by ldmpub** [comment]
Hi,

As far as I understand the fix is now deployed (see https://github.com/WeblateOrg/weblate/milestone/136) but the display bug is still visible under Android in Gmail client => see:

![Image](https://github.com/user-attachments/assets/1e9ab8f0-e7c7-486a-bf60-b8e0b01254ff)

ping @nijel @meel-hd

**Comment by meel-hd** [comment]
I'm testing this on different clients, to know what it is the exact issue

**Comment by ldmpub** [comment]
Eager to receive new notification emails for event "String is available for translation" **after June 15th** _(*)_.

Thanks 😍,

_(*) [Weblate Release 5.2](https://github.com/WeblateOrg/weblate/milestone/141) planned milestone_

**Comment by nijel** [comment]
The fix is just being deployed at Hosted Weblate :-).

**Comment by ldmpub** [comment]
@meel-hd @nijel 

I'm happy to confirm you that footer is now at the bottom in emails received in Gmail under Android => see screen shot of a notification received this morning 🎉.

![Image](https://github.com/user-attachments/assets/e535cb19-e2b4-4f37-bebc-ad04fd750a17)

Thanks a lot for the fix!

**Comment by meel-hd** [comment]
Amazing, our pleasure!
