### ISSUE TITLE
Installation instructions for RHEL cannot be followed due to missing dependencies

### ISSUE THREAD

**Issue by lukasgabriel** [WeblateOrg/weblate#15112]
### Describe the issue

The instructions at https://docs.weblate.org/en/latest/admin/install/venv-redhat.html cannot be completed on RHEL 9 due to package conflicts and unavailable dependencies. Since there is no compatibility matrix, the necessary dependencies cannot be verified.

Unavailable packages:

- xmlsec1-devel
- apache2-mod_wsgi
- fusefs-libs
- libsasl2-devel
- xxhash-devel
- libtool-ltdl-devel
- gobject-introspection-devel
- libyaml-devel

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Try to install Weblate on RHEL 9 using the official documentation.

### Expected behavior

The commands in the docs work and the dependencies can resolve

### Exception traceback

```pytb

```

### How do you run Weblate?

Other

### Weblate deploy checks

```shell

```

**Comment by nijel** [comment]
The differences between releases should not be that big to need a compatibility matrix, most likely there are some issues by reusing package names from other distros. I've just fixed one of that in 219122cb0b.

Can you please clarify, what errors do you get so that we can look into actual problematic packages?

**Comment by lukasgabriel** [comment]
Unfortunately, the issue persists, in regards to the `xmlsec` dependency.

Here are the detailed logs:
```
(weblate-env) [wblservice@hostname ~]$ uv pip install "weblate[all]" --native-tls
Using Python 3.9.21 environment at: weblate-env
Resolved 148 packages in 3.06s
  × Failed to build `xmlsec==1.3.15`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/py.typed -> build/lib.linux-x86_64-cpython-39/xmlsec
      running build_ext
      building 'xmlsec' extension
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/constants.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/constants.o -g -std=c99
      -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/ds.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/ds.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/enc.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/enc.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.o -g -std=c99
      -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os

      [stderr]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/setuptools_scm/_integration/pyproject_reading.py", line
      36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
      KeyError: 'setuptools_scm'
      /opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License
      classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c: In function ‘PyXmlSec_ExchangeLastError’:
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c:76:9: warning: variable ‘r’ set but not used
      [-Wunused-but-set-variable]
         76 |     int r;
            |         ^
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c: In function ‘PyXmlSec_KeyFromEngine’:
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c:218:65: error: ‘xmlSecKeyDataFormatEngine’
      undeclared (first use in this function); did you mean ‘xmlSecKeyDataFormat’?
        218 |         key->handle = xmlSecCryptoAppKeyLoad(engine_and_key_id, xmlSecKeyDataFormatEngine, NULL,
      xmlSecCryptoAppGetDefaultPwdCallback(), (void*)engine_and_key_id);
            |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
            |                                                                 xmlSecKeyDataFormat
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c:218:65: note: each undeclared identifier is
      reported only once for each function it appears in
      error: command '/usr/bin/gcc' failed with exit code 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `xmlsec` (v1.3.15) was included because `weblate[all]` (v5.4.3) depends on `python3-saml` (v1.16.0) which depends on `xmlsec`
```

We then tried with an older `xmlsec` version:
```
(weblate-env) [wblservice@hostname ~]$ uv pip install "weblate[all]" --native-tls
Using Python 3.9.21 environment at: weblate-env
Resolved 148 packages in 3.06s
  × Failed to build `xmlsec==1.3.15`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-cpython-39/xmlsec
      copying src/xmlsec/py.typed -> build/lib.linux-x86_64-cpython-39/xmlsec
      running build_ext
      building 'xmlsec' extension
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/constants.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/constants.o -g -std=c99
      -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/ds.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/ds.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/enc.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/enc.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.o -g -std=c99
      -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe
      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2
      -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g
      -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong
      -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv
      -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
      -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_MD5=1
      -DXMLSEC_NO_SHA1=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.15
      -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/extlibs
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libxml
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/lxml/includes/libexslt
      -I/opt/app/.cache/uv/builds-v0/.tmpZsth5i/include -I/usr/include/python3.9 -c
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c -o
      build/temp.linux-x86_64-cpython-39/opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.o -g -std=c99 -fPIC
      -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os

      [stderr]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "/opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/setuptools_scm/_integration/pyproject_reading.py", line
      36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
      KeyError: 'setuptools_scm'
      /opt/app/.cache/uv/builds-v0/.tmpZsth5i/lib64/python3.9/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License
      classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c: In function ‘PyXmlSec_ExchangeLastError’:
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/exception.c:76:9: warning: variable ‘r’ set but not used
      [-Wunused-but-set-variable]
         76 |     int r;
            |         ^
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c: In function ‘PyXmlSec_KeyFromEngine’:
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c:218:65: error: ‘xmlSecKeyDataFormatEngine’
      undeclared (first use in this function); did you mean ‘xmlSecKeyDataFormat’?
        218 |         key->handle = xmlSecCryptoAppKeyLoad(engine_and_key_id, xmlSecKeyDataFormatEngine, NULL,
      xmlSecCryptoAppGetDefaultPwdCallback(), (void*)engine_and_key_id);
            |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
            |                                                                 xmlSecKeyDataFormat
      /opt/app/.cache/uv/sdists-v9/pypi/xmlsec/1.3.15/ive_u9LKxfobe_ARbYZwi/src/src/keys.c:218:65: note: each undeclared identifier is
      reported only once for each function it appears in
      error: command '/usr/bin/gcc' failed with exit code 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `xmlsec` (v1.3.15) was included because `weblate[all]` (v5.4.3) depends on `python3-saml` (v1.16.0) which depends on `xmlsec`
(weblate-env) [wblservice@de1-s270 ~]$ uv pip install "weblate[all]" xmlsec==1.3.13 --native-tls
Using Python 3.9.21 environment at: weblate-env
Resolved 148 packages in 204ms
      Built pycairo==1.28.0
      Built xmlsec==1.3.13                                                                                                                        × Failed to build `pygobject==3.52.3`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `mesonpy.build_wheel` failed (exit status: 1)

      [stdout]
      + meson setup /opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src
      /opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src/.mesonpy-fmkygjb1
      -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback
      --native-file=/opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src/.mesonpy-fmkygjb1/meson-python-native-file.ini
      The Meson build system
      Version: 1.8.2
      Source dir: /opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src
      Build dir: /opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src/.mesonpy-fmkygjb1
      Build type: native build
      Project name: pygobject
      Project version: 3.52.3
      C compiler for the host machine: cc (gcc 11.5.0 "cc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-5)")
      C linker for the host machine: cc ld.bfd 2.35.2-63
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python3 found: YES (/opt/app/.cache/uv/builds-v0/.tmplTFEVU/bin/python)
      Found pkg-config: YES (/usr/bin/pkg-config) 1.7.3
      Run-time dependency python found: YES 3.9
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency girepository-2.0 found: NO (tried pkgconfig and cmake)
      Not looking for a fallback subproject for the dependency girepository-2.0 because:
      Use of fallback dependencies is disabled.

      ../meson.build:31:9: ERROR: Dependency 'girepository-2.0' is required but not found.

      A full log can be found at
      /opt/app/.cache/uv/sdists-v9/pypi/pygobject/3.52.3/s0KUteCOBpV3_dBKVULyP/src/.mesonpy-fmkygjb1/meson-logs/meson-log.txt

      hint: This usually indicates a problem with the package or the build environment.
  help: `pygobject` (v3.52.3) was included because `weblate` (v5.4.3) depends on `pygobject`
```

Thank you for your support 🙏🏻

**Comment by nijel** [comment]
Let's followup in https://github.com/orgs/WeblateOrg/discussions/15163
