### ISSUE TITLE
Compose "Full name" from "First name" and "Last name"

### ISSUE THREAD

**Issue by martinberanek** [WeblateOrg/weblate#1831]
### Steps to reproduce
1. use LDAP authentication
2. Administration -> Users shows correctly firstname and lastname
![image](https://user-images.githubusercontent.com/13366239/35804286-69bebd7c-0a77-11e8-998a-2b0e8c8d0fec.png)

### Actual behaviour
- in profile, full name contains only firstname
- in git commits, only firstname and email is used
- in page header, only  firstname is present

### Expected behaviour
- concatenate firstname and lastname for fullname (in all cases)

### Server configuration
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.7
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
Please adjust LDAP authentication configuration to match our example, that should fix it:

https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication

See also https://github.com/WeblateOrg/weblate/issues/812 and https://github.com/WeblateOrg/weblate/issues/401

**Comment by martinberanek** [comment]
Unfortunately, this does not solve the problem. Currently we don't have any attribute in LDAP that contains full person name in required format (same as we use in git). I was thinking about implementing custom handler for `django_auth_ldap.backend.populate_user` signal. Can you recommend me some clean solution how to do it? (i'm just java developer without experience with python/django)

**Comment by nijel** [comment]
Actually we can handle it quite gracefully with current django_auth_ldap, I'll push the fix soon.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
