### ISSUE TITLE
Bitbucket webhook goes in error 400 on ping

### ISSUE THREAD

**Issue by fede91it** [WeblateOrg/weblate#1958]
### Steps to reproduce
1. Create a project
2. Creating a component linked to a Bitbucket repository
3. Register http://example.com/hooks/bitbucket/ as repository's webhook
4. Perform a push request that adds a new language

### Actual behaviour
The webhook sent by Bitbucket returns error 400 "Invalid data in json payload!"

### Expected behaviour
The webhook runs without errors

### Payload
```txt
{
	"push": {
		"changes": [{
			"forced": false,
			"old": {
				"type": "branch",
				"name": "master",
				"links": {
					"commits": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commits/master"
					},
					"self": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/refs/branches/master"
					},
					"html": {
						"href": "https://bitbucket.org/f_liva/vivicity/branch/master"
					}
				},
				"target": {
					"hash": "ebb09015458e0be56b205f2935a8578be1794fb9",
					"links": {
						"self": {
							"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/ebb09015458e0be56b205f2935a8578be1794fb9"
						},
						"html": {
							"href": "https://bitbucket.org/f_liva/vivicity/commits/ebb09015458e0be56b205f2935a8578be1794fb9"
						}
					},
					"author": {
						"raw": "Federico Liva <fede91it@gmail.com>",
						"type": "author",
						"user": {
							"username": "fede91it",
							"type": "user",
							"display_name": "Federico Liva",
							"uuid": "{7aaf6b14-e1dd-4418-9c9c-0afd503f3248}",
							"links": {
								"self": {
									"href": "https://api.bitbucket.org/2.0/users/fede91it"
								},
								"html": {
									"href": "https://bitbucket.org/fede91it/"
								},
								"avatar": {
									"href": "https://bitbucket.org/account/fede91it/avatar/32/"
								}
							}
						}
					},
					"summary": {
						"raw": "Aggiunta opzione per eliminare i prodotti prima di sincronizzarli\n\n",
						"markup": "markdown",
						"html": "<p>Aggiunta opzione per eliminare i prodotti prima di sincronizzarli</p>",
						"type": "rendered"
					},
					"parents": [{
						"type": "commit",
						"hash": "f9b76958cd0ad2f0a0f6230a75987afd33a644ee",
						"links": {
							"self": {
								"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/f9b76958cd0ad2f0a0f6230a75987afd33a644ee"
							},
							"html": {
								"href": "https://bitbucket.org/f_liva/vivicity/commits/f9b76958cd0ad2f0a0f6230a75987afd33a644ee"
							}
						}
					}],
					"date": "2018-04-09T14:10:06+00:00",
					"message": "Aggiunta opzione per eliminare i prodotti prima di sincronizzarli\n\n",
					"type": "commit"
				}
			},
			"links": {
				"commits": {
					"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commits?include=3d39786599aaa14eae45202915405a8627f32be7&exclude=ebb09015458e0be56b205f2935a8578be1794fb9"
				},
				"html": {
					"href": "https://bitbucket.org/f_liva/vivicity/branches/compare/3d39786599aaa14eae45202915405a8627f32be7..ebb09015458e0be56b205f2935a8578be1794fb9"
				},
				"diff": {
					"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/diff/3d39786599aaa14eae45202915405a8627f32be7..ebb09015458e0be56b205f2935a8578be1794fb9"
				}
			},
			"truncated": false,
			"commits": [{
				"hash": "3d39786599aaa14eae45202915405a8627f32be7",
				"links": {
					"self": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/3d39786599aaa14eae45202915405a8627f32be7"
					},
					"comments": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/3d39786599aaa14eae45202915405a8627f32be7/comments"
					},
					"patch": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/patch/3d39786599aaa14eae45202915405a8627f32be7"
					},
					"html": {
						"href": "https://bitbucket.org/f_liva/vivicity/commits/3d39786599aaa14eae45202915405a8627f32be7"
					},
					"diff": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/diff/3d39786599aaa14eae45202915405a8627f32be7"
					},
					"approve": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/3d39786599aaa14eae45202915405a8627f32be7/approve"
					},
					"statuses": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/3d39786599aaa14eae45202915405a8627f32be7/statuses"
					}
				},
				"author": {
					"raw": "Federico Liva <fede91it@gmail.com>",
					"type": "author",
					"user": {
						"username": "fede91it",
						"type": "user",
						"display_name": "Federico Liva",
						"uuid": "{7aaf6b14-e1dd-4418-9c9c-0afd503f3248}",
						"links": {
							"self": {
								"href": "https://api.bitbucket.org/2.0/users/fede91it"
							},
							"html": {
								"href": "https://bitbucket.org/fede91it/"
							},
							"avatar": {
								"href": "https://bitbucket.org/account/fede91it/avatar/32/"
							}
						}
					}
				},
				"summary": {
					"raw": "Aggiunta lingua russo (da attivare)\n\n",
					"markup": "markdown",
					"html": "<p>Aggiunta lingua russo (da attivare)</p>",
					"type": "rendered"
				},
				"parents": [{
					"type": "commit",
					"hash": "ebb09015458e0be56b205f2935a8578be1794fb9",
					"links": {
						"self": {
							"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/ebb09015458e0be56b205f2935a8578be1794fb9"
						},
						"html": {
							"href": "https://bitbucket.org/f_liva/vivicity/commits/ebb09015458e0be56b205f2935a8578be1794fb9"
						}
					}
				}],
				"date": "2018-04-11T09:48:15+00:00",
				"message": "Aggiunta lingua russo (da attivare)\n\n",
				"type": "commit"
			}],
			"created": false,
			"closed": false,
			"new": {
				"type": "branch",
				"name": "master",
				"links": {
					"commits": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commits/master"
					},
					"self": {
						"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/refs/branches/master"
					},
					"html": {
						"href": "https://bitbucket.org/f_liva/vivicity/branch/master"
					}
				},
				"target": {
					"hash": "3d39786599aaa14eae45202915405a8627f32be7",
					"links": {
						"self": {
							"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/3d39786599aaa14eae45202915405a8627f32be7"
						},
						"html": {
							"href": "https://bitbucket.org/f_liva/vivicity/commits/3d39786599aaa14eae45202915405a8627f32be7"
						}
					},
					"author": {
						"raw": "Federico Liva <fede91it@gmail.com>",
						"type": "author",
						"user": {
							"username": "fede91it",
							"type": "user",
							"display_name": "Federico Liva",
							"uuid": "{7aaf6b14-e1dd-4418-9c9c-0afd503f3248}",
							"links": {
								"self": {
									"href": "https://api.bitbucket.org/2.0/users/fede91it"
								},
								"html": {
									"href": "https://bitbucket.org/fede91it/"
								},
								"avatar": {
									"href": "https://bitbucket.org/account/fede91it/avatar/32/"
								}
							}
						}
					},
					"summary": {
						"raw": "Aggiunta lingua russo (da attivare)\n\n",
						"markup": "markdown",
						"html": "<p>Aggiunta lingua russo (da attivare)</p>",
						"type": "rendered"
					},
					"parents": [{
						"type": "commit",
						"hash": "ebb09015458e0be56b205f2935a8578be1794fb9",
						"links": {
							"self": {
								"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity/commit/ebb09015458e0be56b205f2935a8578be1794fb9"
							},
							"html": {
								"href": "https://bitbucket.org/f_liva/vivicity/commits/ebb09015458e0be56b205f2935a8578be1794fb9"
							}
						}
					}],
					"date": "2018-04-11T09:48:15+00:00",
					"message": "Aggiunta lingua russo (da attivare)\n\n",
					"type": "commit"
				}
			}
		}]
	},
	"repository": {
		"scm": "git",
		"website": "",
		"name": "vivicity",
		"links": {
			"self": {
				"href": "https://api.bitbucket.org/2.0/repositories/f_liva/vivicity"
			},
			"html": {
				"href": "https://bitbucket.org/f_liva/vivicity"
			},
			"avatar": {
				"href": "https://bitbucket.org/f_liva/vivicity/avatar/32/"
			}
		},
		"project": {
			"links": {
				"self": {
					"href": "https://api.bitbucket.org/2.0/teams/f_liva/projects/LAR"
				},
				"html": {
					"href": "https://bitbucket.org/account/user/f_liva/projects/LAR"
				},
				"avatar": {
					"href": "https://bitbucket.org/account/user/f_liva/projects/LAR/avatar/32"
				}
			},
			"type": "project",
			"uuid": "{84abb462-097e-4ddf-87ce-5456692c4e57}",
			"key": "LAR",
			"name": "Laravel"
		},
		"full_name": "f_liva/vivicity",
		"owner": {
			"username": "f_liva",
			"type": "team",
			"display_name": "Federico Liva",
			"uuid": "{1fc62dcd-4fe7-4729-8c15-b3c62e9fe7f2}",
			"links": {
				"self": {
					"href": "https://api.bitbucket.org/2.0/teams/f_liva"
				},
				"html": {
					"href": "https://bitbucket.org/f_liva/"
				},
				"avatar": {
					"href": "https://bitbucket.org/account/f_liva/avatar/32/"
				}
			}
		},
		"type": "repository",
		"is_private": true,
		"uuid": "{06df31f9-0712-45da-aa7f-9e9431eb979a}"
	},
	"actor": {
		"username": "fede91it",
		"type": "user",
		"display_name": "Federico Liva",
		"uuid": "{7aaf6b14-e1dd-4418-9c9c-0afd503f3248}",
		"links": {
			"self": {
				"href": "https://api.bitbucket.org/2.0/users/fede91it"
			},
			"html": {
				"href": "https://bitbucket.org/fede91it/"
			},
			"avatar": {
				"href": "https://bitbucket.org/account/fede91it/avatar/32/"
			}
		}
	}
}
```

**Comment by nijel** [comment]
I can not reproduce any problem with the payload you've posted. What Weblate version do you use? Can you check Weblate logs for more detailed error message?

**Comment by fede91it** [comment]
Version 2.20

Where can I find logs?

**Comment by nijel** [comment]
By default it logs to syslog, so you should find it in `/var/log/syslog`.

**Comment by dsnoeck** [comment]
I have a similar issue. Using bitbucket 5.9.1 and Weblate 3.0.1 Here is the log I get:

`<bitbucket-ip> - - [20/Jun/2018:06:50:22 +0000] "POST /hooks/bitbucket/ HTTP/1.1" 400 29 "-" "Atlassian HttpClient 1.1.0 / Bitbucket-5.9.1 (5009001) / Default"
`
Here is the request
```
{  
  "request":{  
    "url":"http://<my-hosted-weblate-server>/hooks/bitbucket/",
    "body":null,
    "method":"POST",
    "headers":{  
      "X-Request-Id":"a7ef4752-cb35-4aef-972e-159e2cbe81cd",
      "X-Event-Key":"diagnostics:ping"
    }
  },
  "response":{  
    "status":400,
    "headers":{  
      "X-Frame-Options":"SAMEORIGIN",
      "Server":"nginx/1.10.3 (Ubuntu)",
      "Connection":"keep-alive",
      "Vary":"Accept-Language, Cookie",
      "Content-Length":"29",
      "Date":"Wed, 20 Jun 2018 06:50:22 GMT",
      "Content-Language":"en",
      "Via":"1.1 localhost (Apache-HttpClient/4.5.5 (cache))",
      "Content-Type":"text/html; charset=UTF-8"
    },
    "body":"Could not parse JSON payload!"
  }
}
```

**Comment by nijel** [comment]
Thanks for providing additional details, this should be easy to fix.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by dsnoeck** [comment]
Also, I find that it will not work with a self hosted bitbucket. in file trans/views/api.py, method bitbucket_webhook_helper() the return object should contain for key repo_url: data['repository']['links']['self']['href'] (see my request body in my comment from your commit bf023c7ab6f186d5433d0ab1ad61e0087c3aa909) Also You have a fixed list of hosted bitbucket server. I don't know if exactly how it is working. So let me know if you need more debug data.

**Comment by nijel** [comment]
I think I've addressed all issues, but guessing repository URL from `data['repository']['links']['self']['href']` really looks fragile, unfortunately there is no repository URL provided in the webhook payload.

**Comment by dsnoeck** [comment]
Thanks a lot for your update. Unfortunately, it is still not working. I also have tried with an other repo then in my own workspace and I think the problem is because bitbucket build the path by adding a `/scm`. For example, in the component configuration (in weblate), the repo value is set to: http://<username>:<password>@<hostname>/scm/<project>/<repo>.git
I know, I should use ssh-key to avoid adding username/pwd.

**Comment by nijel** [comment]
The username should not be problem, the problem probably is the /scm/ in the path...

**Comment by dsnoeck** [comment]
And know that I'm using ssh-key ;-) the repo value looks like: `ssh://git@<hostname>:<port>/<project>/<repo>.git`
The closest guess in weblate is: `ssh://git@<hostname>/<PROJECT>/<repo>.git` which is missing the port number and the project is in uppercase. I will try to find a fix.

**Comment by nijel** [comment]
I have no clue how to figure out these information from the notification data. The perfect in this are GitHub notifications which include all project clone URLs and there is nothing left to guess.

**Comment by dsnoeck** [comment]
Ticket created at Atlassian: https://bitbucket.org/site/master/issues/16563/add-more-information-in-the-webhook
In the meantime, I have try to hack your code and I was able to make it work by updating the query:
```
for repo in repos:
        if repo.startswith('ssh://git@'):
            spfilter = spfilter | (
                Q(repo__startswith='ssh://git@' + urlparse(repo_url).hostname) &
                Q(repo__icontains=service_data['full_name']) # return object should contains full_name
            )
```
With that, it will not fail if there is a different PORT, and repo_icontains is case insensitive.
I will create a PR.
