### ISSUE TITLE
automatic msgmerge wraps differently than translation commits

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#1987]
Ok!  Another chapter in the Wonderful World of Whitespace!  Translate commits seem to be doing the right thing in terms of wrapping:

```diff
Translated using Weblate (French)

-------------------- locale/fr/LC_MESSAGES/fdroidserver.po --------------------
index 7bc4216..a81e051 100644
@@ -1,21 +1,20 @@
 # SOME DESCRIPTIVE TITLE.
 # Copyright (C) YEAR Free Software Foundation, Inc.
 # FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
 #
 msgid ""
 msgstr ""
 "Project-Id-Version: fdroidserver 0.9\n"
-"Report-Msgid-Bugs-To: https://gitlab.com/fdroid/fdroidserver/issues\n"
+"Report-Msgid-Bugs-To: team@f-droid.org\n"
 "POT-Creation-Date: 2018-02-13 09:01+0100\n"
-"PO-Revision-Date: 2018-04-21 06:37+0000\n"
-"Last-Translator: Sébastien SOUALMIA <ssoualmia@gmail.com>\n"
-"Language-Team: French <https://hosted.weblate.org/projects/f-droid/"
-"fdroidserver/fr/>\n"
+"PO-Revision-Date: 2018-04-25 14:38+0000\n"
+"Last-Translator: Étienne Deparis <etienne@depar.is>\n"
+"Language-Team: French <https://hosted.weblate.org/projects/f-droid/fdroidserver/fr/>\n"
 "Language: fr\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=2; plural=n > 1;\n"
 "X-Generator: Weblate 3.0-dev\n"
 
 #: ../fdroidserver/nightly.py
```

Then right afterwards, there is a _msgmerge_ commit which changes the wrapping back:

```diff
Update translation files
    
Updated by Update PO files to match POT (msgmerge) hook in Weblate.

-------------------- locale/fr/LC_MESSAGES/fdroidserver.po --------------------
index a81e051..7e005a5 100644
@@ -1,20 +1,21 @@
 # SOME DESCRIPTIVE TITLE.
 # Copyright (C) YEAR Free Software Foundation, Inc.
 # FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
 #
 msgid ""
 msgstr ""
 "Project-Id-Version: fdroidserver 0.9\n"
-"Report-Msgid-Bugs-To: team@f-droid.org\n"
+"Report-Msgid-Bugs-To: https://gitlab.com/fdroid/fdroidserver/issues\n"
 "POT-Creation-Date: 2018-02-13 09:01+0100\n"
 "PO-Revision-Date: 2018-04-25 14:38+0000\n"
 "Last-Translator: Étienne Deparis <etienne@depar.is>\n"
-"Language-Team: French <https://hosted.weblate.org/projects/f-droid/fdroidserver/fr/>\n"
+"Language-Team: French <https://hosted.weblate.org/projects/f-droid/"
+"fdroidserver/fr/>\n"
 "Language: fr\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=2; plural=n > 1;\n"
 "X-Generator: Weblate 3.0-dev\n"
 
 #: ../fdroidserver/nightly.py
```

Here are some examples that are in https://hosted.weblate.org/git/f-droid/fdroidserver right now:
* a790ae3652a49cbcf582c9d12859c9346e3715e3
* cdbcf34ca815e2380d259658f3fea72f80d30ed7
* 0c3ebf2dbe713456e34089bacf021e8cd15305b5
* 0fd41048865690c6b8de54388d97f30d4a80797f

This is related to #1884

**Comment by nijel** [comment]
This should be already fixed in the translate-toolkit (see https://github.com/translate/translate/pull/3773), did you see this recently?

**Comment by eighthave** [comment]
The commits I referred to are from this week.  Its on
hosted.weblate.org, and says ` "X-Generator: Weblate 3.0-dev\n"`

**Comment by nijel** [comment]
Okay, the issue is indeed fixed in the translate-toolkit, I just forgot to deploy the fix on Hosted Weblate. It should now work fine.

Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by eighthave** [comment]
I'm still seeing this in https://hosted.weblate.org/projects/f-droid/fdroidserver/.  It seems that there are two processes in weblate doing the wrap differently.  This happened last at 2019-01-19.  That component has  the "Customize gettext output" set to "only wrap lines at newlines".  When a translator commits, that seems to do the right thing:

```diff
diff --git a/locale/it/LC_MESSAGES/fdroidserver.po b/locale/it/LC_MESSAGES/fdroidserver.po
index af89e53..1b06fa6 100644
--- a/locale/it/LC_MESSAGES/fdroidserver.po
+++ b/locale/it/LC_MESSAGES/fdroidserver.po
@@ -6,18 +6,17 @@
 msgid ""
 msgstr ""
 "Project-Id-Version: fdroidserver 0.9\n"
-"Report-Msgid-Bugs-To: https://gitlab.com/fdroid/fdroidserver/issues\n"
+"Report-Msgid-Bugs-To: team@f-droid.org\n"
 "POT-Creation-Date: 2018-07-13 11:05+0200\n"
-"PO-Revision-Date: 2018-05-21 15:54+0000\n"
-"Last-Translator: random r <epsilin@yopmail.com>\n"
-"Language-Team: Italian <https://hosted.weblate.org/projects/f-droid/"
-"fdroidserver/it/>\n"
+"PO-Revision-Date: 2018-12-31 23:09+0000\n"
+"Last-Translator: Matteo Fumagalli <f.mustang@protonmail.com>\n"
+"Language-Team: Italian <https://hosted.weblate.org/projects/f-droid/fdroidserver/it/>\n"
 "Language: it\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=2; plural=n != 1;\n"
-"X-Generator: Weblate 3.0-dev\n"
+"X-Generator: Weblate 3.4-dev\n"
 
 #: ../fdroidserver/nightly.py
 msgid ""
```
But then there is a follow up commit called "Update translation files" that breaks it again:

```diff
diff --git a/locale/it/LC_MESSAGES/fdroidserver.po b/locale/it/LC_MESSAGES/fdroidserver.po
index 1b06fa6..ecf93ad 100644
--- a/locale/it/LC_MESSAGES/fdroidserver.po
+++ b/locale/it/LC_MESSAGES/fdroidserver.po
@@ -6,11 +6,12 @@
 msgid ""
 msgstr ""
 "Project-Id-Version: fdroidserver 0.9\n"
-"Report-Msgid-Bugs-To: team@f-droid.org\n"
+"Report-Msgid-Bugs-To: https://gitlab.com/fdroid/fdroidserver/issues\n"
 "POT-Creation-Date: 2018-07-13 11:05+0200\n"
 "PO-Revision-Date: 2018-12-31 23:09+0000\n"
 "Last-Translator: Matteo Fumagalli <f.mustang@protonmail.com>\n"
-"Language-Team: Italian <https://hosted.weblate.org/projects/f-droid/fdroidserver/it/>\n"
+"Language-Team: Italian <https://hosted.weblate.org/projects/f-droid/"
+"fdroidserver/it/>\n"
 "Language: it\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
```


(FYI Linguine task) @matrixcoffee

**Comment by nijel** [comment]
Ah, I somehow didn't notice the msgmerge part in the original report as I was aware of other issue in line wrapping in the po file...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
