### ISSUE TITLE
Adding new translation string

### ISSUE THREAD

**Issue by GeorgeBekh** [WeblateOrg/weblate#2027]
### Steps to reproduce
1. Go to the source language in your component
2. Go to Tools -> Add new translation string
3. Write something, press "Process"
4. Go to Manage -> Repository maintenance

### Actual behaviour
```
Repository status:
There are some uncommitted changes!
...
```
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   {source lang}.po

no changes added to commit (use "git add" and/or "git commit -a")
```
Cannot commit changes because they are not staged

### Expected behaviour
Updated file should be commited or at least staged for commit so they can be synced with remote repo

### Server configuration
Installed from https://github.com/WeblateOrg/docker.git

**Comment by GeorgeBekh** [comment]
Is it the expected behaviour or a bug? If it's expected, what do i do wrong?

**Comment by nijel** [comment]
Does the commit button work? It can happen that Weblate leaves uncommitted files on the disk, it tries to postpone the commit to reduce number of commits.

**Comment by GeorgeBekh** [comment]
Hi! Thanks for answering! I think it works, my guess is it does just `git commit`, not `git commit -a` so it leaves unstaged changes intact, so after i press it the message about unstaged changes persists

**Comment by nijel** [comment]
It should add files which were changed, so probably something is not working as expected there.

**Comment by GeorgeBekh** [comment]
I've tried to commit it manually on server with `git commit -a` and it worked with no errors or something

**Comment by nijel** [comment]
Now I probably understand that, I believe it should be fixed by 13667795dfbebba4faef9c2c8f8486c8101e969a (and related commits). It would be great if you could verify that.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by GeorgeBekh** [comment]
Ok, thanks! i'll try to check it out

Also i'm not sure if there is a typo in your commit: https://github.com/WeblateOrg/weblate/commit/13667795dfbebba4faef9c2c8f8486c8101e969a#r29110114

**Comment by GeorgeBekh** [comment]
I've currently tested this on master branch, it seems that problem still persists.

**Comment by nijel** [comment]
I've managed to reproduce it now and it should be really fixed, testing is welcome :-).

**Comment by GeorgeBekh** [comment]
It works, thanks!

**Comment by nijel** [comment]
BTW: There was one more issue with that, I've fixed it in  935aedb
