### ISSUE TITLE
Celery errors dbm.error: cannot add item to database

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2730]
**Describe the bug**
Each modification in weblate takes about 35 seconds to finish.

**To Reproduce**
1. Go to any component and change a string
2. Change content and validate the string
3. The next page will take a while before displaying.

**Expected behavior**
Each record should take less than a few seconds before.

**Server configuration and status**
```
(venv) weblate@ynh:~$ weblate list_versions
 * Weblate 3.5.1
 * Python 3.5.3
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * hub 2.3.0-pre10
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://127.0.0.1:6379/2, redis://127.0.0.1:6379/2, regular
 * Platform: Linux 4.9.0-9-amd64 (x86_64)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f101224eae8>
Traceback (most recent call last):
  File "/var/www/weblate/venv/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f101224eae8>
Traceback (most recent call last):
  File "/var/www/weblate/venv/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

```
(venv) weblate@ynh:~$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E009) The Celery tasks queue is too long, either the worker is not running or is too slow.
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#celery

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors

System check identified 3 issues (0 silenced).
```

**Additional context**
Here is the log:
```
# cat celery-w1.log | grep "2019-05-08"
[2019-05-08 15:47:12,896: DEBUG/MainProcess] Canceling task consumer...
[2019-05-08 15:47:13,252: INFO/MainProcess] beat: Shutting down...
[2019-05-08 15:47:19,353: DEBUG/MainProcess] Canceling task consumer...
[2019-05-08 15:47:19,354: DEBUG/MainProcess] Closing consumer channel...
[2019-05-08 15:47:19,917: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2019-05-08 15:47:21,408: WARNING/MainProcess] Exception ignored in:
[2019-05-08 15:47:21,542: WARNING/MainProcess] <celery.utils.log.LoggingProxy object at 0x7f215ce246d8>
[2019-05-08 15:47:21,542: WARNING/MainProcess] Traceback (most recent call last):
[2019-05-08 15:47:21,542: WARNING/MainProcess] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/utils/log.py", line 249, in flush
[2019-05-08 15:47:21,645: WARNING/MainProcess] def flush(self):
[2019-05-08 15:47:21,655: WARNING/MainProcess] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
[2019-05-08 15:47:21,658: WARNING/MainProcess] raise exc(exitcode)
[2019-05-08 15:47:21,666: WARNING/MainProcess] celery.exceptions
[2019-05-08 15:47:21,667: WARNING/MainProcess] .
[2019-05-08 15:47:21,667: WARNING/MainProcess] WorkerShutdown
[2019-05-08 15:47:21,667: WARNING/MainProcess] :
[2019-05-08 15:47:21,668: WARNING/MainProcess] 0
[2019-05-08 15:47:49,586: INFO/Beat] beat: Starting...
[2019-05-08 15:47:49,741: ERROR/Beat] Process Beat
[2019-05-08 15:47:49,814: WARNING/Beat] Process Beat:
[2019-05-08 15:47:49,815: WARNING/Beat] Traceback (most recent call last):
[2019-05-08 15:47:49,815: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
[2019-05-08 15:47:49,816: WARNING/Beat] KeyError: 'scheduler'
[2019-05-08 15:47:49,816: WARNING/Beat] During handling of the above exception, another exception occurred:
[2019-05-08 15:47:49,817: WARNING/Beat] Traceback (most recent call last):
[2019-05-08 15:47:49,817: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 111, in __getitem__
[2019-05-08 15:47:49,817: WARNING/Beat] KeyError: 'entries'
[2019-05-08 15:47:49,817: WARNING/Beat] During handling of the above exception, another exception occurred:
[2019-05-08 15:47:49,818: WARNING/Beat] Traceback (most recent call last):
[2019-05-08 15:47:49,818: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 515, in _create_schedule
[2019-05-08 15:47:49,818: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 113, in __getitem__
[2019-05-08 15:47:49,819: WARNING/Beat] KeyError: b'entries'
[2019-05-08 15:47:49,819: WARNING/Beat] During handling of the above exception, another exception occurred:
[2019-05-08 15:47:49,819: WARNING/Beat] Traceback (most recent call last):
[2019-05-08 15:47:49,820: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/billiard/process.py", line 327, in _bootstrap
[2019-05-08 15:47:49,820: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 664, in run
[2019-05-08 15:47:49,820: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 579, in start
[2019-05-08 15:47:49,820: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
[2019-05-08 15:47:49,821: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 623, in scheduler
[2019-05-08 15:47:49,821: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 618, in get_scheduler
[2019-05-08 15:47:49,821: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 458, in __init__
[2019-05-08 15:47:49,821: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 225, in __init__
[2019-05-08 15:47:49,822: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 486, in setup_schedule
[2019-05-08 15:47:49,822: WARNING/Beat] File "/var/www/weblate/venv/lib/python3.5/site-packages/celery/beat.py", line 519, in _create_schedule
[2019-05-08 15:47:49,822: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
[2019-05-08 15:47:49,822: WARNING/Beat] _dbm.error: cannot add item to database
[2019-05-08 15:47:49,843: WARNING/Beat] Exception ignored in:
[2019-05-08 15:47:49,843: WARNING/Beat] <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f58b92bb588>>
[2019-05-08 15:47:49,844: WARNING/Beat] Traceback (most recent call last):
[2019-05-08 15:47:49,844: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 162, in __del__
[2019-05-08 15:47:49,845: WARNING/Beat] self.close()
[2019-05-08 15:47:49,847: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 144, in close
[2019-05-08 15:47:49,847: WARNING/Beat] self.sync()
[2019-05-08 15:47:49,848: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 168, in sync
[2019-05-08 15:47:49,849: WARNING/Beat] self[key] = entry
[2019-05-08 15:47:49,849: WARNING/Beat] File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
[2019-05-08 15:47:49,850: WARNING/Beat] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2019-05-08 15:47:49,850: WARNING/Beat] _dbm
[2019-05-08 15:47:49,850: WARNING/Beat] .
[2019-05-08 15:47:49,850: WARNING/Beat] error
[2019-05-08 15:47:49,851: WARNING/Beat] :
[2019-05-08 15:47:49,851: WARNING/Beat] cannot add item to database
[2019-05-08 15:47:50,143: INFO/MainProcess] Connected to redis://127.0.0.1:6379/2
[2019-05-08 15:47:50,164: INFO/MainProcess] mingle: searching for neighbors
[2019-05-08 15:47:51,213: INFO/MainProcess] mingle: all alone
```

Here are the scripts describing how I run the celery daemon and the parameters:

* https://github.com/YunoHost-Apps/weblate_ynh/blob/master/conf/celery-weblate.service
* https://github.com/YunoHost-Apps/weblate_ynh/blob/master/conf/celery-weblate

**Comment by nijel** [comment]
The dbm error is something what occasionally happens in Celery. See https://github.com/WeblateOrg/weblate/issues/2615 or https://github.com/WeblateOrg/weblate/issues/2421 or several issues in Celery (for example https://github.com/celery/celery/issues/5447).

What worked well for the docker image in the end was installing the python3-gdbm package.

**Comment by Jibec** [comment]
I confirm the issue is now solved thanks to the `python3-gdbm` package :)

**Comment by nijel** [comment]
Thanks for confirming, I've updated docs to mention that.

**Comment by Kaju-Bubanja** [comment]
This did not fix the issue for me. I have following installed and the issue persists

```
ii  libgdbm-compat4:amd64                 1.14.1-6                                        amd64        GNU dbm database routines (legacy support runtime version) 
ii  libgdbm5:amd64                        1.14.1-6                                        amd64        GNU dbm database routines (runtime version) 
ii  python3-gdbm:amd64                    3.6.7-1~18.04                                   amd64        GNU dbm database support for Python 3.x

```
