### ISSUE TITLE
If Android strings.xml contains Entity, fails to create component

### ISSUE THREAD

**Issue by Viish** [WeblateOrg/weblate#2843]
**Describe the bug**
If Android strings.xml contains Entity, fails to create component:
`
app/src/main/res/values/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable
`

**To Reproduce**
Using weblate 3.7 (installed right now through pip / virtualenv)
Try to create a translation component from a git repository containing an Android app in which the strings.xml contains the following:
`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE resources [
    <!ENTITY appName "Linphone">
]>

<resources>
    
    <string name="app_name">&appName;</string>
</resources>`
You can test yourselves with https://gitlab.linphone.org/BC/public/linphone-android on branch feature/trying_to_use_entity_in_resources

**Expected behavior**
It should load the file and allow translations.

Thanks in advance.

**Comment by Viish** [comment]
I attached a screenshot, even with code tool my sample doesn't render correctly...
![Screenshot_20190628_161758](https://user-images.githubusercontent.com/1561996/60348656-53c99080-99c0-11e9-8383-ab3550d9e738.png)

**Comment by nijel** [comment]
Bug confirmed, the [translate-toolkit](https://github.com/translate/translate/) fails to parse such files.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported is addressed in https://github.com/translate/translate/pull/3915.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Viish** [comment]
That's very nice of you, thanks !

**Comment by Viish** [comment]
I've tried to setup a weblate (master) with a translate submodule with your changes, but I still have the issue:
`attribute 'text' of 'lxml.etree._Entity' objects is not writable`

**Comment by Viish** [comment]
If I can be of any help feel free to contact me.

**Comment by nijel** [comment]
It seems like you're not actually using the patched version.

**Comment by Viish** [comment]
I checked twice and cleaned/re-created my virtual env somewhere else to be sure.
I've checkout the master branch of weblate, clone the submodules, go to the translate submodule and changed the commit to the one in your merge request.
![Screenshot_20190813_160940](https://user-images.githubusercontent.com/1561996/62948582-eb563780-bde4-11e9-9ef8-6ce4b9ad4a19.png)
![Screenshot_20190813_160834](https://user-images.githubusercontent.com/1561996/62948585-ec876480-bde4-11e9-9099-533c3467eee9.png)

**Comment by nijel** [comment]
Okay, that's definitely not the module being used :-). The submodules there are used to build language data, not by runtime - you actually do not need any submodules for that.

You can install the patched branch using pip:

```
pip install https://github.com/nijel/translate/archive/android-entity.zip
```

**Comment by Viish** [comment]
Oh ! Thanks a lot for the help, I wouldn't have figured it out by myself !

It now successfully parse the resource file with the entity, but then it doesn't accept the translation of a string using it.

For example, consider the following string: "$appName; friends". In french, I'd like to translate that by "$appName; amis" for example. But weblate try to automatically substitute $appName; by it's value and if I force in the translation $appName; it doesn't accept it.
My strings have a little '!' next to it with "string has failed verifications" or something like that.

The best would be to keep the $appName; everywhere and simply ask for a translation of $appName; once.

**Comment by nijel** [comment]
What you mean that it automatically substitutes it? It should parse it as a string and save as well.

You can add `ignore-same` flag to strings you expect not to be changed.

**Comment by Viish** [comment]
Forget about the substitution part, I miss understood what happened. It was just the previous translation...
However there is an issue anyway that if the translation contains $appName; sometimes it will fail saving it (sometimes not) and even if it saves it the translation isn't exported in the translation file (the others are fine).

**Comment by nijel** [comment]
What happens when it fails? Do you get some error?
