### ISSUE TITLE
Notification "Summary: new component alert" / 1 bug + 1 question

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#2860]
**Context**
Email "Résumé : Alerte de nouveau composant" received, see french email screenshot => 
![Notification Weblate](https://user-images.githubusercontent.com/1452146/60753671-7d914180-9fd6-11e9-898b-2d15819c97fe.jpg)

**Bug 1 - Describe the bug**
Column user (utilisateur) contains a not translated string despite Weblate in 100% translated to french => see screenshot

**Bug 1 - Expected behavior**
Use a translation key for this column

**Question**
What's the purpose of these notifications? Can you give me a clear description what is called a Component in Weblate? Is there a way to remove these notifications (in my profile) because they look like there are for admin who should monitor sync between Weblate and CVS?

Thanks,

**Comment by nijel** [comment]
This notification should be enabled only for projects you administer, so you've probably enabled this manually. What is your notification settings for component alerts?

The localization issue was fixed in 4a288f25d1.

**Comment by nijel** [comment]
Closing this issue as the bug was fixed.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ldmpub** [comment]
Hi,

Thanks for the bug fix.

I have disabled these notifications because I still do not understand why I'm notified (I'm not an admin!) and what does "new component" means.

![No Notification](https://user-images.githubusercontent.com/1452146/60773326-11146080-a104-11e9-9cd0-2e3d3ad8ad43.jpg)

**Comment by nijel** [comment]
It means "new alert for component", see https://docs.weblate.org/en/latest/devel/alerts.html

I can see you have disabled these for now, so you should not get any further notifications on these.

**Comment by ldmpub** [comment]
Thanks for the link to the documentation (I searched but didn't find it).

French translation changed and suggestion added in source string to change it to "New alert for component" like describe bu Michal above ; see https://hosted.weblate.org/translate/weblate/master/fr/?checksum=584a55c41efc5c7c

**Comment by nijel** [comment]
I've rather made it just "New alert" in 178a14f92d...
