### ISSUE TITLE
Notifications are sent to deleted users

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3139]
**Describe the bug**
When trying to delete a user in django admin interface (Home > Authentication > User), the user is not deleted but rather updated and suddenly gets username and Email similar to:
- username: deleted-6
- email: noreply+6@weblate.org

**To Reproduce**
1. Go to `django admin interface > Home > Authentication > User`
2. Select a user (tick check-box)
   - [x] TestUser
3. From `Action dropdown` select `Delete selected users` ... ten press `Go`
4. User is not deleted but rather updated:
![image](https://user-images.githubusercontent.com/8058166/67358114-a32f6000-f55f-11e9-97ea-d7c0a727ab0c.png)

**Expected behavior**
User (in this case `TestUser`) clearly gets deleted and removed from the user's list.

**Screenshots**
see above

**Server configuration and status**

- Weblate as docker image from hub.docker.com, from tag: `3.9-1`
- Postgres DB version `10.7`
- Redis version `5.0.4`

```
$ weblate list_versions
 * Weblate 3.9
 * Python 3.7.3
 * Django 2.2.6
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 6.2.0
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * tesserocr 2.4.1
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * hub 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: email-smtp.eu-west-1.amazonaws.com
 * Celery: redis://weblate-oc-cache-service-ext:6379/1, redis://weblate-oc-cache-service-ext:6379/1, regular
 * Platform: Linux 3.10.0-957.21.3.el7.x86_64 (x86_64)
```

```
 weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E027) Path /app/data/lost+found is owned by different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/weblate-3.9/admin/install.html#file-permissions

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.9/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.9/admin/backup.html

System check identified 4 issues (1 silenced).
```

**Comment by nijel** [comment]
This is expected behavior. The reason is data consistency - when really removing the user all related changes, comments, suggestions would be removed. This way they are kept with reference to the deleted user.

**Comment by rhofer** [comment]
Ok got it. The ugly thing is e.g. for email sending, weblate then trys sending email to e.g. deleted-6 hence `noreply+6@weblate.org` ... what ends up in undeliverable email: `An error occurred while trying to deliver the mail to the following recipients:
noreply+6@weblate.org
`

Would suggest that weblate is not doing any actions with deleted users, as e.g. email.

**Comment by nijel** [comment]
Good point.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rhofer** [comment]
Just tested with docker image 3.9.1-1 . It still sends out email to deleted user. Additionally tried following:
- create valid user, set user to "inactive" first, then delete user : still sends email to deleted user
- delete again already deleted user : still sends email to deleted user

Can it be the the if statement for `not user.is_active` doesn't apply, somehow? Is this really taking the `active` status from the deleted user?

**Comment by nijel** [comment]
Ah now I see. What I've fixed are generic notification, not the audit log ones.

**Comment by nijel** [comment]
This should be addressed by 740d005d79fd990774b344762dd242e8f0448c9f

**Comment by rhofer** [comment]
Tried to re-test with weblate 3.9.1-3 (from hub.docker.com). Still failing.

@nijel is this fix in 3.9.1-3 ?

**Comment by nijel** [comment]
I think this was not backported to the Docker image, it will be part of the 3.10 release on Friday.

**Comment by rhofer** [comment]
Tried to re-test with weblate 3.10.3-1 from hub.docker.com. Still failing with bounce back email for user "deleted--15" saying:

"An error occurred while trying to deliver the mail to the following recipients: noreply+15@weblate.org"

@nijel on my side it still doesn't work as it is supposed to (do not send email to deleted user). Am I doing something wrong? Or is there any configuration for this I missed? Can you confirm this from a testinstance from your side?

**Comment by nijel** [comment]
There should not be any configuration needed for this. Can you please check the bounce what kind of notification does it contain?

**Comment by nijel** [comment]
I've addressed some (unlikely) cases in a64885ca6802d933b9b42a3a6512381a740b8da1, but still it would be useful to see what kind of notification did it trigger for you.

**Comment by rhofer** [comment]
I get the follow notification of type Report:

From: MAILER-DEMON@xyz...
To: My admin email inbox
Subject: Undeliverable: [My weblate instance] Activity on your account at [My weblate instance]
Body:
An error occurred while trying to deliver the mail to the followint recipients:
[noreply+15@weblate.org](mailto:noreply+15@weblate.org)

**Comment by nijel** [comment]
The body should include what kind of activity it is about, that's the most important bit (sorry for note being clear enough in first question).

**Comment by rhofer** [comment]
If I extraced this correctly from my Outlook msg, then it should be this part:

```
There has been a change in your account at [My weblate instance]:

Account and all private data removed.

...
IP address | xxx.xxx.xxx.xxx
---|---
Useragent|PC/Windows10/Chrome79.0.3945

If you did not request this change, please report it as soon as possible.

[Report suspicious activity](/contact/?t=account)

![](cid:email-logo-footer.png@cid.weblate.org)
[Weblate ,the libre continuous localization system.](https://weblate.org/)

▸[Notificationsettings](/accounts/profile/#notifications)

GeneratedonFeb.10,2020,4:58a.m.
```

And apparantly, it tried to send this to `deleted+15@weblate.org`

**Comment by nijel** [comment]
Should be fixed by 29f9b0d6f57577bbfc789a4ff162aae9fb1b93ea

**Comment by rhofer** [comment]
Many thanks for the fix. Tested with weblate 3.11-1. Works as expected.
