### ISSUE TITLE
Wrong "Failed checks" raised?

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#3321]
Hi,

Can someone have a look to https://hosted.weblate.org/translate/osmand/main/fr/?q=has:check
where 80 fails checks are raised but there is no info on each strings with the exact fail ;-(.

Note: some of these strings have the same translation than the source string (for instance for the one word strings "scooter") which is ok for me / the translator.

Thanks for your help (and hoping it's not a big bug but rather a "little" bug or maybe wrong settings in the OsmAnd project itself).

**Comment by nijel** [comment]
Seems the flags were wrongly calculated for some reason. First I thought that it is related to recent data migration, but it was present even in previous data, so it's hard to track now when it was triggered. Anyway I've fixed the flags for now.

**Comment by ldmpub** [comment]
Thanks to have taken this issue into account and to confirm is not only linked to the project itself.
Yet I still see "80 Fails Checks".

**Comment by nijel** [comment]
Hmm, apparently it has appeared again, so there has to be some bug somewhere...

**Comment by ldmpub** [comment]
Good luck and tell me if I can help ;-)

**Comment by ldmpub** [comment]
I confirm => this bug is closed. Many thanks!
