### ISSUE TITLE
Format check confuses singular and plural forms

### ISSUE THREAD

**Issue by rmol** [WeblateOrg/weblate#4655]
**Describe the bug**

I configured the Python brace format check for our project, and was surprised to see it complaining about a [translation](https://weblate.securedrop.org/translate/securedrop/securedrop/fr/?checksum=e9d246cf825cbb7d) that seemed to include a variable in a format string correctly. Only the plural version of the source string contains the variable, and the variable only appears in the plural translation. (The screenshot below is clearer than my explanation. :slightly_smiling_face:) This looks right to me.

I am really not well versed in the subtleties of pluralization, but I think [`BaseFormatCheck.check_generator`](https://github.com/WeblateOrg/weblate/blob/e5a2be37ed8d8ef1de249deca580e112fbedca69/weblate/checks/format.py#L237) might work better if it never compared a plural source to singular target. 

**To Reproduce**

Create a source string with singular and plural versions, with a counter variable only appearing in the plural version. Translate both, only repeating the counter variable in the plural translation. Enable a format check for the component or source string, and observe that it complains about the format string, though it's translated correctly.

**Expected behavior**

I would have expected the format check to not complain about this translation.

**Screenshots**

![weblate-python-brace-plural-problem](https://user-images.githubusercontent.com/47430598/95258376-a749a180-07f3-11eb-90ab-4251d209eb3e.png)

**Server configuration and status**

We're running Weblate 4.1.1 and it's otherwise working fine.

**Comment by nijel** [comment]
This case is already fixed in Weblate 4.2: https://github.com/WeblateOrg/weblate/commit/68cb5fe5f9ecdb901f26a5ca32af4725287c6492

**Comment by rmol** [comment]
We just upgraded to 4.3.2 and are still seeing this check failing on [what look like proper translations](https://weblate.securedrop.org/translate/securedrop/securedrop/fr/?checksum=1f68fb09967362ea).

**Comment by nijel** [comment]
The checks are not immediately updated on upgrade. You can force updating using [updatechecks](https://docs.weblate.org/en/latest/admin/management.html#updatechecks).

**Comment by rmol** [comment]
Ah, sorry. Running `updatechecks` sorted them out. Thanks!
