### ISSUE TITLE
gitlab webhooks no longer working 

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#5032]
**Describe the issue**

We are using weblate in a dockerized environment and since we've upgraded from version 3.x to 4.3 out gitlab hooks are no longer working. When I refresh the repo in the GUI it's working but the hooks are not. We are using PO files with weblate POT extension.

**I already tried**
- read the docs and added ENABLE_HOOKS=1 (in 3.x it worked without that)
- enabled DEBUG
- searched the web without any result

**To Reproduce**
- self explaining IMHO

**Expected behavior**

the project will be updated 

**Screenshots**

![image](https://user-images.githubusercontent.com/7972273/102060744-dc293480-3df2-11eb-8222-f8fff04c9a41.png)

**Server configuration and status**
 * Weblate: 4.3
 * Django: 3.1.2
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.1.1
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.2
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.19.0
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.9
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.15.16
 * zeep: 4.0.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Redis server: 4.0.14
 * PostgreSQL server: 9.6.19
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.cape-it.de
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.16.0-4-amd64 (x86_64)

**Weblate deploy checks**

docker-compose exec --user weblate weblate weblate check --deploy doesn't return, so here are the log entries
![image](https://user-images.githubusercontent.com/7972273/102061730-1d6e1400-3df4-11eb-9290-94427ed73be1.png) 

**Exception traceback**
- no exceptions

**Additional context**
- none

**Comment by nijel** [comment]
The problem is that you request /hooks/gitlab which redirects to /hooks/gitlab/, but the redirection leads to GET being used instead of POST. It seems to be the nginx causing redirection, it might be related to https://github.com/WeblateOrg/docker/pull/857, can you try upgrading your container?

**Comment by ReneBoehm** [comment]
After the update of all images and the restart, the issue still exists.

**Comment by ReneBoehm** [comment]
reg. de trailing slash...it doesn't work in both cases, with or without trailing slash

**Comment by ReneBoehm** [comment]
Ok, I've used the recommendation from WeblateOrg/docker#857 mounted a patched default.tpl file, where the second server config is removed. Now the hooks are working again.

**Comment by nijel** [comment]
The fix is part of newer container, upgrade should resolve that without need for manual patching (I've already mentioned this in https://github.com/WeblateOrg/weblate/issues/5032#issuecomment-744455690).

**Comment by ReneBoehm** [comment]
I've seen that but it didn't solve the issue for me. See my comment above (https://github.com/WeblateOrg/weblate/issues/5032#issuecomment-745404400). Did a `docker-compose pull`, images got downloaded and the stack has been restarted. Problem still existed. But I can try again.

**Comment by ReneBoehm** [comment]
OK, did the update again and it downloaded a new image. Now the issue is solved using the defaults. Don't know what image got downloaded yesterday when I've tried that recommendation.
