### ISSUE TITLE
Translations are lost when not committing and pushing right after adding the new translation string before staring to translate it

### ISSUE THREAD

**Issue by jochen-jung** [WeblateOrg/weblate#6890]
### Describe the issue

Steps to reproduce:

Create a new translation string in german language.

Then add a translation for this string. For example for dutch.

Commit and push the changes.

Now go back to german language and search for the translation key.

It is there. However the dutch translation is missing. It is not even possible anymore to add a dutch translation from now on, as it is no longer listed under 'other languages'.

Attached is a video of what I did. In the end you can see that dutch is no longer listed as 'other languages'.

There is a workaround.

It works fine, when you commit and push right after adding the initial german version of the string and only after that start writing on the translation.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Screenshots

https://user-images.githubusercontent.com/408273/144030424-283d7fc5-4548-4a22-9881-c27a2d0970d9.mp4

### How do you run Weblate?

Other

### Weblate versions

Weblate 4.9

**Comment by nijel** [comment]
I think we fixed something similar in 4.9.1, can you try upgrading?

**Comment by nijel** [comment]
Also, are you using some add-ons?

**Comment by kidwm** [comment]
@nijel I still encountered similar problem in 4.9.1 with these steps:

1. Go to source locale `en`, under `Files/Upload translation` with `Add new strings` to upload several new keys in JSON file.

2. modify the JSON file to translate into the other language.

3. Go to the other locale, under `Files/Upload translation` with `Add as translation` to upload translated content in the JSON file.

sometime it would report that strings are not found, I have to repeat the step 3 to upload it again to make it imported as expected.

**Comment by jochen-jung** [comment]
Yes, the problem still exists with 4.9.1 installed. I will check which addons we have installed.

**Comment by nijel** [comment]
@kidwm Your issue is different, most likely caused by bug that made Weblate add new strings as translated (matching the source string). This is fixed by 99f6b16.

**Comment by m2mtech** [comment]
FYI the described behavior is still present in the most recent [docker release 4.10.1-1](https://github.com/WeblateOrg/docker/releases/tag/4.10.1-1).

In detail for projects which do not want the remote-vcs functionality of weblate I wrote an [translation-provider-bundle for symfony](https://github.com/m2mtech/weblate-translation-provider/) which pushes and pulls translations via the weblate api. Creating components and translations worked without problem. But adding new units via the api to the source language showed the behavior described above. 

First everything looks fine, the translation languages show the missing stings. Translation works, too. As soon as the translation language is committed - the translated strings disappear and cannot be recovered any more. 

I ended up pushing complete files instead of adding individual units. 

Deleting/changing units via the api showed no problems.

Thank you for your great project!

**Comment by nijel** [comment]
@m2mtech I've added the translation provider to our docs in b023074043.

As for the bug, the issue as described in the initial comment has been really fixed by 80635a1. I've added tests covering this in edba65407756bb727da6514390bde362b22237d1. Maybe you were doing something differently?

**Comment by m2mtech** [comment]
... I used the api:

1. added the source (en) component via `POST /api/projects/(string: project)/components/` using `docfile` with `xliff 1.2`
2. added the translation (de) via `POST /api/components/(string: project)/(string: component)/translations/`
3. added the translations manually via the WEB interrace
4. committed the changes manually via the WEB interrace
5. added a source string via `POST /api/translations/(string: project)/(string: component)/(string: language)/units/`
6. added the translation manually via the WEB interface
7. committed the change manually via the WEB interrace

After step 6. the translation of the last edited string is visible.
After step 7. it is gone only the translations from strep 3 are available.

**Comment by nijel** [comment]
What was the component configuration in (1)?

**Comment by m2mtech** [comment]
```php
$formFields = [
            'name' => $domain,
            'slug' => $domain,
            'edit_template' => 'true',
            'manage_units' => 'true',
            'source_language' => self::$defaultLocale,
            'file_format' => 'xliff',
            'docfile' => new DataPart($content, $domain.'/'.self::$defaultLocale.'.xlf'),
        ];
```
