### ISSUE TITLE
Source text in history (changes) event is always the same as the latest source text

### ISSUE THREAD

**Issue by Geeyun-JY3** [WeblateOrg/weblate#7171]
### Describe the issue

Source text in history (changes) event is always same as the latest source text. It may confused users.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Shown in everywhere the event shown, such as `History` tab of any target string translate page, changes page.

### Expected behavior

Show the source text at that time.

### Screenshots
Example: https://hosted.weblate.org/translate/weblate/hosted-error-pages/zh_Hans/?checksum=92048f2895471655
![image](https://user-images.githubusercontent.com/49396421/151514053-d002ec83-734e-4485-bf87-4e77c3e250dd.png)

### How do you run Weblate?

weblate.org service

**Comment by Geeyun-JY3** [comment]
@nijel Still can reproduce this bug.
Example: https://hosted.weblate.org/translate/skytube/strings/zh_Hans/?checksum=e6764355a05958c4

**Comment by nijel** [comment]
Should be fixed by 10f3c4ed60

**Comment by Geeyun-JY3** [comment]
@nijel It seems that this bug is still not completely fixed.
A recent example: https://hosted.weblate.org/translate/f-droid/f-droid/zh_Hans/?checksum=8ffca01dbdaf4d5a#history

**Comment by nijel** [comment]
The previous source string was not stored before https://github.com/WeblateOrg/weblate/commit/790d8dd85264c3878b37fec20d17d928a50d15fd, so it is expected for old changes to not have matching source string...

**Comment by Geeyun-JY3** [comment]
Got it. Thanks for explanation.

**Comment by Geeyun-JY3** [comment]
@nijel Still can reproduce this bug in the suggestion-related event.

Example: https://hosted.weblate.org/translate/libretube/libretube/zh_Hans/?checksum=82bebea27ebe8cd8#history
The corresponding source text of suggestion added in 2022-06-10T12:44:48+00:00 should be `There is a new update available. Click okay to become redirected to the update page on GitHub.`
![image](https://user-images.githubusercontent.com/49396421/174522442-136a27a0-c216-489b-821b-a74a29baa4e6.png)

I guess all the suggestion-related events(Suggestion accepted, Suggestion added, Suggestion removed, Suggestion removed during cleanup) have this bug.
BTW, I think storing the previous source strings may not be enough for the fixes for Suggestion accepted events. A warning dialog may be needed.

**Comment by nijel** [comment]
That one should be fixed in 4ebf4c9a74
