### ISSUE TITLE
The latest version of docker bleeding does not start

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#7745]
### Describe the issue

The latest version of docker bleeding does not start

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Additional context

https://sentry.io/share/issue/3844225c7fbf4c04817eb89ee2aefbec/

**Comment by nijel** [comment]
Should be already fixed by 6b0c9030b56171160fd00a8a4980910386882a72

**Comment by tomkolp** [comment]
Today I tried to update again, I still have the same error.
https://sentry.io/share/issue/3844225c7fbf4c04817eb89ee2aefbec/

**Comment by nijel** [comment]
What git revision do you run? (Sometimes the daily image is not built and published)

**Comment by tomkolp** [comment]
https://hub.docker.com/layers/weblate/weblate/weblate/bleeding-2022-06-06-8110c4752653e714eba76fbc0a3c5acc90ca5283/images/sha256-ca452f2693bc608ffa1fd8ced58a76c2b58e3170a9d5ba6b723617a120cc918d?context=explore

**Comment by tomkolp** [comment]
@nijel I'm doing the updates now, still the same error.

**Comment by nijel** [comment]
0bf0f144e6 shold fix that

**Comment by tomkolp** [comment]
I will test how the new Bleeding Docker image will be, because today's image has not been published.

**Comment by nijel** [comment]
Yes, I've messed up the tests (but it would not include this fix anyway).

**Comment by tomkolp** [comment]
Works :)
